the-way:
  core:
    log: true
  log:
    level: 0
  server:
    enabled: true
    port: 8080
    api-endpoint: '/api'
    security:
      user-key: '12345678901234567890123456789012'
      token-key: '12345678901234567890123456789034'
    file:
      enabled: false
      fallback: false
      full: false
      path: ''
      static: 
        path: ''
        full: false
      assets: 
        path: ''
        full: false