the-way:
  core:
    log: true
  log:
    level: 0
  server:
    enabled: true
    port: 8081
    path: /api
    swagger:
      enabled: true
      path: /swagger
      title: Amazing Swagger
      description: i'm inevitable
      outputPath: ./dist/src/main/swagger.json
      version: 1.0.0
      filesMatcher: './*.rest.ts'
      type:
        name: 'openapi'
        version: 3.0.0
      contact:
        name: The Way
    security:
      user-key: A2345678901234567890123456789012
      token-key: B2345678901234567890123456789034
      token-expiration: '3 days'
    file:
      enabled: false
      fallback: false
      full: false
      path: ''
      static: 
        path: ''
        full: false
      assets: 
        path: ''
        full: false