the-way:
    scan:
        path: 'src/main'
        full: false
        enabled: true
    core:
        log:
            enabled: true
            level: 0
        language: 'en'
    server:
        enabled: true
        operations-log: true
        http:
            port: 80
            enabled: true
        https:
            port: 443
            enabled: false
            keyPath: ''
            certPath: ''
        helmet:
            enabled: true
        cors:
            enabled: true
            origin: true
        rest:
            path: /api
            security:
                user-key: A2345678901234567890123456789012
                token-key: B2345678901234567890123456789034
                token-expiration: '3 days'
            swagger:
                enabled: false
                path: /swagger
                filePath: './swagger.json'
        file:
            enabled: false
            fallback: false
            full: false
            path: ''
            static:
                path: ''
                full: false
                enabled: false
            assets:
                path: ''
                full: false
                enabled: false